export const SKILLS_LIST = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'React',
  'Vue.js',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Node.js',
  'Express.js',
  'Deno',
  'Python',
  'Django',
  'Flask',
  'Ruby',
  'Ruby on Rails',
  'PHP',
  'Laravel',
  'GraphQL',
  'REST APIs',
  'Apollo',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Firebase',
  'Prisma',
  'Docker',
  'Kubernetes',
  'AWS',
  'Google Cloud',
  'Azure',
  'Vercel',
  'Netlify',
  'Tailwind CSS',
  'Bootstrap',
  'Sass',
  'LESS',
  'Jest',
  'Cypress',
  'Testing Library',
  'Git',
  'GitHub',
  'CI/CD',
];

export const SOFT_SKILLS_LIST = [
  'Communication',
  'Teamwork',
  'Problem-solving',
  'Time management',
  'Critical thinking',
  'Decision-making',
  'Organizational',
  'Stress management',
  'Adaptability',
  'Creativity',
  'Leadership',
  'Interpersonal',
  'Work ethic',
  'Attention to detail',
];
