export const SKILLS_LIST = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'React',
  'Vue.js',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Node.js',
  'Express.js',
  'Deno',
  'Python',
  'Django',
  'Flask',
  'Ruby',
  'Ruby on Rails',
  'PHP',
  'Laravel',
  'GraphQL',
  'REST APIs',
  'Apollo',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Firebase',
  'Prisma',
  'Docker',
  'Kubernetes',
  'AWS',
  'Google Cloud',
  'Azure',
  'Vercel',
  'Netlify',
  'Tailwind CSS',
  'Bootstrap',
  'Sass',
  'LESS',
  'Jest',
  'Cypress',
  'Testing Library',
  'Git',
  'GitHub',
  'CI/CD',
  // DS/AI
  'Jupyter',
  'Pandas',
  'NumPy',
  'Scikit-learn',
  'TensorFlow',
  'PyTorch',
  // UI/UX
  'Figma',
  'Adobe XD',
  'Sketch',
  // QA
  'Selenium',
  'Playwright',
];

export const SOFT_SKILLS_LIST = [
  'Communication',
  'Teamwork',
  'Problem-solving',
  'Time management',
  'Critical thinking',
  'Decision-making',
  'Organizational',
  'Stress management',
  'Adaptability',
  'Creativity',
  'Leadership',
  'Interpersonal',
  'Work ethic',
  'Attention to detail',
];

export const CAREER_SKILLS: { [key: string]: string[] } = {
  software_engineering: [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Node.js',
    'Next.js',
    'Python',
    'Django',
    'Flask',
    'SQL',
    'PostgreSQL',
    'MongoDB',
    'Firebase',
    'Docker',
    'Kubernetes',
    'AWS',
    'Git',
    'GitHub',
    'CI/CD',
    'REST APIs',
    'GraphQL',
  ],
  data_science: [
    'Python',
    'R',
    'SQL',
    'Jupyter',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'TensorFlow',
    'PyTorch',
    'Matplotlib',
    'Seaborn',
    'AWS',
    'Azure',
    'Google Cloud',
    'Docker',
  ],
  qa_engineering: [
    'JavaScript',
    'Python',
    'Java',
    'Selenium',
    'Cypress',
    'Playwright',
    'Jest',
    'Testing Library',
    'Postman',
    'Jira',
    'CI/CD',
    'Git',
    'SQL',
  ],
  cyber_security: [
    'Python',
    'Bash',
    'Networking',
    'Linux',
    'Wireshark',
    'Metasploit',
    'Nmap',
    'SQL',
    'Cryptography',
    'Security Information and Event Management (SIEM)',
  ],
  ui_ux: [
    'Figma',
    'Adobe XD',
    'Sketch',
    'User Research',
    'Wireframing',
    'Prototyping',
    'HTML',
    'CSS',
    'JavaScript',
    'User-centered design',
    'Interaction Design',
  ],
  product_management: [
    'Jira',
    'Agile',
    'Scrum',
    'Roadmapping',
    'User Research',
    'Data Analysis',
    'A/B Testing',
    'SQL',
    'Communication',
    'Leadership',
  ],
  devops: [
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Google Cloud',
    'Terraform',
    'Ansible',
    'CI/CD',
    'Jenkins',
    'GitHub Actions',
    'Prometheus',
    'Grafana',
    'Python',
    'Bash',
    'Linux',
  ],
};
